apiVersion: v1
kind: Service
metadata:
  name: rota-gateway
  namespace: rota
  labels:
    app: rota-gateway
spec:
  type: ClusterIP
  selector:
    app: rota-gateway
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: None
